#达梦
spring:
  datasource:
    driverClassName: dm.jdbc.driver.DmDriver
    url: jdbc:dm://localhost:5236/dm8?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
    username: SYSDBA
    password: SYSDBA